### ISSUE TITLE
Improve error message 2!

### ISSUE THREAD

**Issue by B0pol** [iv-org/invidious#1507]
https://github.com/iv-org/invidious/pull/1504 has improved the error message but it still can be improved.
The current system will flood the github issues with **long** crash reports.

An easy way to counter this is to use `<details>` and `<summary>` HTML tags ([relevant documentation](https://developer.mozilla.org/fr/docs/Web/HTML/Element/details)).

Example with a crash report from NewPipe:

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ FR
* __Content Language:__ fr-FR
* __App Language:__ fr_FR
* __Service:__ none
* __Version:__ 0.20.1
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Error receiving broadcast Intent { act=org.schabi.newpipe.VideoDetailFragment.ACTION_PLAYER_STARTED flg=0x10 } in org.schabi.newpipe.fragments.detail.VideoDetailFragment$4@4feadd9
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1401)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.schabi.newpipe/.player.MainPlayer }: app is in background uid UidRecord{1b3bf85 u0a590 CAC  bg:+2m34s765ms idle procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1577)
	at android.app.ContextImpl.startService(ContextImpl.java:1532)
	at android.content.ContextWrapper.startService(ContextWrapper.java:664)
	at org.schabi.newpipe.player.helper.PlayerHolder.startService(PlayerHolder.java:59)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$4.onReceive(VideoDetailFragment.java:1343)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1391)
	... 8 more

```
</details>
<hr>

Plain text (I broke the `  on purpose):

```

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ FR
* __Content Language:__ fr-FR
* __App Language:__ fr_FR
* __Service:__ none
* __Version:__ 0.20.1
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

`` `
java.lang.RuntimeException: Error receiving broadcast Intent { act=org.schabi.newpipe.VideoDetailFragment.ACTION_PLAYER_STARTED flg=0x10 } in org.schabi.newpipe.fragments.detail.VideoDetailFragment$4@4feadd9
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1401)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.schabi.newpipe/.player.MainPlayer }: app is in background uid UidRecord{1b3bf85 u0a590 CAC  bg:+2m34s765ms idle procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1577)
	at android.app.ContextImpl.startService(ContextImpl.java:1532)
	at android.content.ContextWrapper.startService(ContextWrapper.java:664)
	at org.schabi.newpipe.player.helper.PlayerHolder.startService(PlayerHolder.java:59)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$4.onReceive(VideoDetailFragment.java:1343)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1391)
	... 8 more

`` `
</details>
<hr>
```

## Invidious

The current error report is:

Date: `2020-11-30T19:50:37Z`
Route: `/channel/UCITk7Ky4iE5_xISw9IaHqpQ`
Version: `0.20.1-4acfd2c @ master`
Backtrace: 
```
Missing hash key: "metadata" (KeyError)
  from ../../../usr/lib/crystal/hash.cr:1030:9 in '[]'
  from src/invidious/channels.cr:804:12 in 'get_about_info'
  from src/invidious.cr:2475:15 in '->'
  from ../../../usr/lib/crystal/primitives.cr:255:3 in '->'
  from ../../../usr/lib/crystal/primitives.cr:255:3 in 'call'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from ../../../usr/lib/crystal/http/server.cr:498:5 in '->'
  from ../../../usr/lib/crystal/primitives.cr:255:3 in 'run'
  from ???
```

### Improved version

Now if you add `<details>`:

Date: `2020-11-30T19:50:37Z`
Route: `/channel/UCITk7Ky4iE5_xISw9IaHqpQ`
Version: `0.20.1-4acfd2c @ master`
<details>
<summary>Backtrace</summary><p>

```
Missing hash key: "metadata" (KeyError)
  from ../../../usr/lib/crystal/hash.cr:1030:9 in '[]'
  from src/invidious/channels.cr:804:12 in 'get_about_info'
  from src/invidious.cr:2475:15 in '->'
  from ../../../usr/lib/crystal/primitives.cr:255:3 in '->'
  from ../../../usr/lib/crystal/primitives.cr:255:3 in 'call'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from ../../../usr/lib/crystal/http/server.cr:498:5 in '->'
  from ../../../usr/lib/crystal/primitives.cr:255:3 in 'run'
  from ???
```
</p>
</details>

### plain text (again ` broken on purpose):

```
Date: `2020-11-30T19:50:37Z`
Route: `/channel/UCITk7Ky4iE5_xISw9IaHqpQ`
Version: `0.20.1-4acfd2c @ master`
<details>
<summary>Backtrace</summary><p>

`` `
Missing hash key: "metadata" (KeyError)
  from ../../../usr/lib/crystal/hash.cr:1030:9 in '[]'
  from src/invidious/channels.cr:804:12 in 'get_about_info'
  from src/invidious.cr:2475:15 in '->'
  from ../../../usr/lib/crystal/primitives.cr:255:3 in '->'
  from ../../../usr/lib/crystal/primitives.cr:255:3 in 'call'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from ../../../usr/lib/crystal/http/server.cr:498:5 in '->'
  from ../../../usr/lib/crystal/primitives.cr:255:3 in 'run'
  from ???
`` `
</p>
</details>

**Comment by TheFrenchGhosty** [comment]
@saltycrys @tirz

**Comment by tirz** [comment]
I was pretty happy with https://github.com/iv-org/invidious/pull/1504

Now it may still be improved if we want to have a nice interface in case of crash.
But it should be easy for the user to know which part is interesting for us.
Hiding the backtrace to the users is ok as long as they expend the `<details>` and copy/past its content.

```
* __Version:__ 0.20.1
* __OS:__ Linux Android 9 - 28
```

Is interesting.

```
* __User Action:__ ui error
* __Request:__ App crash, UI failure
```

Is interesting but it need a lot of work.
Also, an UI error is unlikely here since it is an html page and not a Java-GUI library.

```
* __Content Country:__ FR
* __Content Language:__ fr-FR
* __App Language:__ fr_FR
* __Service:__ none
```

Are not relevant here:
 - The country depend of the Invidious instance.
 - The content language is fixed to English.
 - The app language is not really interesting.

**Comment by tirz** [comment]
But yes `<details>` look nicer...
I think it is a good idea.

**Comment by B0pol** [comment]
@tirz I did not meant we should add language, country…

Just `<details>` and I picked an example from NewPipe

**Comment by saltycrys** [comment]
I like it. I also think we should switch to a date based version, currently the only way to tell versions apart is the commit hash. I'll make a PR with both of these changes.

We're getting a lot more error reports now, with many duplicates. We should make sure that even if somebody is reporting a duplicate they still feel good about reporting it, to make sure they keep reporting errors in the future.
